name: 5150 Doc Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - name: Configure PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Build Docs
        run: |
          pnpm install
          pnpm vuepress build docs
        working-directory: ./src
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: deployment-session
          aws-region: us-east-1

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Deploy
        run: |
          npm install
          cdk deploy --require-approval never
        working-directory: ./deployment
