name: 5150 Doc Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install PNPM
        run: npm install -g pnpm
      
      - name: Build Docs
        run: |
          pnpm install
          pnpm vuepress build docs
        working-directory: ./src
